### ISSUE TITLE
Dropping items on purpose doesn't push them forward

### ISSUE THREAD

**Issue by DiamondJMS** [T0RNATO/drop-spread-2#2]
I started playing with the mod so that my items don't spread when I die, but I noticed that even when I drop the item by pressing Q, the item has no push forward and drops at my feet.

**Comment by T0RNATO** [comment]
Oh, yeah. Oops. I'll look into it.

**Comment by T0RNATO** [comment]
This is fixed in 1.0.3
https://modrinth.com/mod/drop-spread-2/version/UfgF5C8v
